### PR TITLE
fix requires

### PR DESCRIPTION
**Pull request by manuelmeurer**
This removes the warning addd in https://github.com/rtomayko/rack-cache/commit/c799703afdf8aab0d169b0b6a64165929d0007c3

### CODE REVIEW

**Comment by marceloboeira** [comment]
@manuelmeurer thanks!

**Comment by manuelmeurer** [comment]
My pleasure! :smile: Could you release a new version please?

**Comment by marceloboeira** [comment]
@manuelmeurer  done!

**Comment by manuelmeurer** [comment]
Thanks! It doesn't seem to be pushed to RubyGems yet though...
https://rubygems.org/gems/redis-rack-cache still shows 1.2.3 as the latest version.

**Comment by marceloboeira** [comment]
I guess @jodosha is the only one with push rights to RubyGems.

**Pull request merged**
